#!/usr/bin/env bash
# Pre-Reqs:
#  sudo apt install jq pipx
#  pipx install gh-release-install (https://github.com/jooola/gh-release-install)
# We're using SNAP which might require systemd
# In /etc/wsl.conf in the linux distro
# [boot]
# systemd=true
# and then do the wsl --shutdown restart dance.
set -eo pipefail

__post_install_step() {
  local cmd="$1"
  local file="$2"
  pushd "$LOCAL_BIN" >/dev/null
  eval "$cmd $file"
  popd >/dev/null
}

install_tools() {
  local files=("$TOOL_CONFIG")
  local tools
  local repo
  local version
  local artifact
  local contents_line
  local extract
  local binary
  local extract_cmdline

  if [[ -n "$DPM_TOOLS_ADDITIONS_YAML" ]]; then
    files+=("$DPM_TOOLS_ADDITIONS_YAML")
  fi
  # shellcheck disable=SC2016
  mapfile -t tools < <(yq_wrapper -p yaml -o json eval-all '. as $item ireduce ({}; . *+ $item)' "${files[@]}" | jq -c ".[]")

  for line in "${tools[@]}"; do
    repo=$(echo "$line" | jq -r '.repo')
    version=$(echo "$line" | jq -r '.version')
    artifact=$(echo "$line" | jq -r '.artifact')
    contents_line=$(echo "$line" | jq -r '.contents')
    post_install=$(echo "$line" | jq -r 'select(.post_install != null) | .post_install')
    extract=$(echo "$contents_line" | cut -f1 -d':')
    binary=$(echo "$contents_line" | cut -f2 -d':')
    binary=${binary:-$extract}
    if [[ -n "$extract" ]]; then
      extract_cmdline="--extract $extract"
    else
      extract_cmdline=""
    fi
    if [[ "$repo" != "null" ]]; then
      if [[ "${installed[$binary]}" != "$version" || ! -x "$LOCAL_BIN/$binary" ]]; then
        echo "[+] $binary@$version from $repo (attempt install)"
        # since extract_cmdline needs to be expanded.
        # shellcheck disable=SC2086
        gh_release_install "$repo" "$artifact" "$LOCAL_BIN/$binary" --version "$version" $extract_cmdline
        if [[ "$post_install" != "" ]]; then
          __post_install_step "$post_install" "$binary"
        fi
        # shellcheck disable=SC2004
        installed[$binary]="$version"
      else
        echo "[=] $binary@$version from $repo (already installed)"
        continue
      fi
    fi
  done
}
