#!/usr/bin/env bash

install_help() {
  cat <<EOF

Usage: just install [$ACTION_LIST]
  tools  Install binary tools from $TOOL_CONFIG
  repos  Install/Update git repos from $REPO_CONFIG
  zips   Install/Update zipfiles from $ZIP_CONFIG
  help   Show this help
EOF
  exit 0
}
