#!/usr/bin/env bash
set -eo pipefail

sdk_install_aws() {
  case "$1" in
  install)
    aws_download_and_run_installer
    aws_download_docker_credential_ecr_login
    aws --version
    ;;
  uninstall | rm)
    sudo rm /usr/local/bin/aws
    sudo rm /usr/local/bin/aws_completer
    sudo rm -rf /usr/local/aws-cli
    echo "Skip deleting ~/.aws (chicken mode)"
    ;;
  update | upgrade)
    aws_download_and_run_installer --update
    aws_download_docker_credential_ecr_login
    aws --version
    ;;
  *)
    echo "Installs / updates the AWS CLI"
    echo "just sdk aws install|rm|update"
    exit 0
    ;;
  esac
}

aws_download_and_run_installer() {
  tmpdir=$(mktemp -d -t awscli.XXXXXX)
  curl -fSsL "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "$tmpdir/awscliv2.zip"
  unzip -q -d "$tmpdir" "$tmpdir/awscliv2.zip"
  (cd "$tmpdir" && sudo ./aws/install "$@")
  rm -rf "$tmpdir"
}

aws_download_docker_credential_ecr_login() {
  mkdir -p ~/.local/bin
  curl -fSsL https://amazon-ecr-credential-helper-releases.s3.us-east-2.amazonaws.com/0.9.0/linux-amd64/docker-credential-ecr-login -o "${HOME}/.local/bin/docker-credential-ecr-login"
  chmod +x "${HOME}/.local/bin/docker-credential-ecr-login"
  echo "Consider adding the following to ~/.docker/config.json"
  printf '{\n  "credHelpers": {\n    "public.ecr.aws": "ecr-login",\n    "<aws_account_id>.dkr.ecr.<region>.amazonaws.com": "ecr-login"\n  }\n}\n'
}
