#!/usr/bin/env bash
set -eo pipefail

#shellcheck disable=SC2002
__configure_tenv() {
  local tofu_v
  tofu_v=$(cat "$SDK_CONFIG" | yq -r ".opentofu.version")
  tenv tofu install "$tofu_v"
  tenv tofu use "$tofu_v"
}

sdk_install_tenv() {
  if which tenv >/dev/null; then
    __configure_tenv
  else
    echo -e "\n>>> Install tenv via 'just install archives' first"
    exit 2
  fi
}
