#!/usr/bin/env bash
set -eo pipefail

#shellcheck disable=SC1091
#shellcheck disable=SC1090
#shellcheck disable=SC2002
sdk_install_nvm() {
  local nvm_v
  local nvm_loc
  # nvm_v=$(gh release list -R nvm-sh/nvm --json "tagName,isPrerelease,isLatest" -q '.[] | select (.isPrerelease == false) |  select (.isLatest == true) | .tagName')
  nvm_v=$(cat "$SDK_CONFIG" | yq -r ".nvm.version")
  if [[ -n "$DPM_SKIP_NVM_PROFILE" ]]; then
    curl -fSsL "https://raw.githubusercontent.com/nvm-sh/nvm/$nvm_v/install.sh" | PROFILE=/dev/null bash
  else
    curl -fSsL "https://raw.githubusercontent.com/nvm-sh/nvm/$nvm_v/install.sh" | bash
  fi
  nvm_loc="$(find "$HOME" -maxdepth 3 -type f -name "nvm.sh")"
  source "$nvm_loc"
  nvm install --lts && nvm use --lts
}
