repos:
  - repo: local
    hooks:
      - id: shfmt
        name: shfmt
        entry: shfmt -i 2 -w
        fail_fast: true
        types: [shell]
        language: system
        stages: [pre-commit]
      - id: shellcheck
        name: shellcheck
        entry: shellcheck
        fail_fast: true
        types: [shell]
        language: system
        stages: [pre-commit]
