# Notes:
# contents == path-to-binary-in-archive:name-of-binary-in-local-bin
# version == could be latest but requires a github_token, usually just the name of the release
# artifact == the name of the artifact in the associated release
# updatecli settings
# updatecli.kind == defaults to 'semver' probably doesn't need to change
# updatecli.pattern == defaults to '*', use a specific version to pin the version
# updatecli.yamlpath == the yamlpath to update; probably should be defaulted.
# updatecli.trim_prefix == defaults to ''
just:
  repo: casey/just
  version: 1.42.4
  artifact: just-{version}-x86_64-unknown-linux-musl.tar.gz
  contents: just
  updatecli:
    yamlpath: $.just.version
    kind: semver
    pattern: "*"
    trim_prefix: v
kubectx:
  repo: ahmetb/kubectx
  version: v0.9.5
  artifact: kubectx_{tag}_linux_x86_64.tar.gz
  contents: kubectx
k9s:
  repo: derailed/k9s
  version: v0.50.9
  artifact: k9s_Linux_amd64.tar.gz
  contents: k9s
terraform-docs:
  repo: terraform-docs/terraform-docs
  version: v0.20.0
  artifact: terraform-docs-{tag}-linux-amd64.tar.gz
  contents: terraform-docs
nova:
  repo: fairwindsops/nova
  version: v3.11.7
  artifact: nova_{version}_linux_amd64.tar.gz
  contents: nova
updatecli:
  repo: updatecli/updatecli
  version: v0.105.1
  artifact: updatecli_Linux_x86_64.tar.gz
  contents: updatecli
tflint:
  repo: terraform-linters/tflint
  version: v0.58.1
  artifact: tflint_linux_amd64.zip
  contents: tflint
gopass:
  repo: gopasspw/gopass
  version: v1.15.16
  artifact: gopass-{version}-linux-amd64.tar.gz
  contents: gopass
tfsummarize:
  repo: dineshba/tf-summarize
  version: v0.3.14
  artifact: tf-summarize_linux_amd64.tar.gz
  contents: tf-summarize
starship:
  repo: starship/starship
  version: v1.23.0
  artifact: starship-x86_64-unknown-linux-gnu.tar.gz
  contents: starship
shellcheck:
  repo: koalaman/shellcheck
  version: v0.11.0
  artifact: shellcheck-{tag}.linux.x86_64.tar.xz
  contents: shellcheck-{tag}/shellcheck:shellcheck
shfmt:
  repo: mvdan/sh
  version: v3.12.0
  artifact: shfmt_{tag}_linux_amd64
  contents: :shfmt
hcledit:
  repo: minamijoyo/hcledit
  version: v0.2.17
  artifact: hcledit_{version}_linux_amd64.tar.gz
  contents: hcledit
tfupdate:
  repo: minamijoyo/tfupdate
  version: v0.9.2
  artifact: tfupdate_{version}_linux_amd64.tar.gz
  contents: tfupdate
gron:
  repo: tomnomnom/gron
  version: v0.7.1
  artifact: gron-linux-amd64-{version}.tgz
  contents: gron
git-cliff:
  repo: orhun/git-cliff
  version: v2.10.0
  artifact: git-cliff-{version}-x86_64-unknown-linux-gnu.tar.gz
  contents: git-cliff-{version}/git-cliff:git-cliff
git-absorb:
  repo: tummychow/git-absorb
  version: 0.8.0
  artifact: git-absorb-{version}-x86_64-unknown-linux-musl.tar.gz
  contents: git-absorb-{version}-x86_64-unknown-linux-musl/git-absorb:git-absorb
committed:
  repo: crate-ci/committed
  version: v1.1.7
  artifact: committed-{tag}-x86_64-unknown-linux-musl.tar.gz
  contents: ./committed:committed
actionlint:
  repo: rhysd/actionlint
  version: v1.7.7
  artifact: actionlint_{version}_linux_amd64.tar.gz
  contents: actionlint
mikefarah-yq:
  repo: mikefarah/yq
  version: v4.47.1
  artifact: yq_linux_amd64
  contents: :yq
mutagen:
  repo: mutagen-io/mutagen
  version: v0.18.1
  artifact: mutagen_linux_amd64_{tag}.tar.gz
  contents: mutagen
lazygit:
  repo: jesseduffield/lazygit
  version: v0.54.2
  artifact: lazygit_{version}_Linux_x86_64.tar.gz
  contents: lazygit
difftastic:
  repo: wilfred/difftastic
  version: 0.64.0
  artifact: difft-x86_64-unknown-linux-gnu.tar.gz
  contents: difft
gitsemver:
  repo: psanetra/git-semver
  version: v1.1.2
  artifact: git-semver_{version}_linux_amd64.tar.gz
  contents: git-semver
iamlive:
  repo: iann0036/iamlive
  version: v1.1.26
  artifact: iamlive-{tag}-linux-amd64.tar.gz
  contents: iamlive
gitleaks:
  repo: gitleaks/gitleaks
  version: v8.28.0
  artifact: gitleaks_{version}_linux_x64.tar.gz
  contents: gitleaks
jf:
  repo: sayanarijit/jf
  version: v0.6.2
  artifact: jf-x86_64-unknown-linux-gnu.tar.gz
  contents: jf
fzf:
  repo: junegunn/fzf
  version: v0.65.1
  artifact: fzf-{version}-linux_amd64.tar.gz
  contents: fzf
fd:
  repo: sharkdp/fd
  version: v10.2.0
  artifact: fd-{tag}-x86_64-unknown-linux-gnu.tar.gz
  contents: fd-{tag}-x86_64-unknown-linux-gnu/fd:fd
bat:
  repo: sharkdp/bat
  version: v0.25.0
  artifact: bat-{tag}-x86_64-unknown-linux-gnu.tar.gz
  contents: bat-{tag}-x86_64-unknown-linux-gnu/bat:bat
snyk:
  repo: snyk/cli
  version: v1.1298.3
  artifact: snyk-linux
  contents: :snyk
drivel:
  repo: hgrsd/drivel
  version: v0.2.2
  artifact: drivel-x86_64-unknown-linux-gnu.tar.xz
  contents: drivel-x86_64-unknown-linux-gnu/drivel:drivel
dive:
  repo: wagoodman/dive
  version: v0.13.1
  artifact: dive_{version}_linux_amd64.tar.gz
  contents: dive
lnav:
  repo: tstack/lnav
  version: v0.13.0
  artifact: lnav-{version}-linux-musl-x86_64.zip
  contents: lnav-{version}/lnav:lnav
xc:
  repo: joerdav/xc
  version: v0.8.6
  artifact: xc_{version}_linux_amd64
  contents: :xc
jaq:
  repo: 01mf02/jaq
  version: v2.3.0
  artifact: jaq-x86_64-unknown-linux-gnu
  contents: :jaq
bkt:
  repo: dimo414/bkt
  version: 0.8.2
  artifact: bkt.v{version}.x86_64-unknown-linux-gnu.zip
  contents: bkt
