# Notes:
# contents == path-to-binary-in-archive:name-of-binary-in-local-bin
# version == could be latest but requires a github_token, usually just the name of the release
# artifact == the name of the artifact in the associated release
# updatecli settings
# updatecli.kind == defaults to 'semver' probably doesn't need to change
# updatecli.pattern == defaults to '*', use a specific version to pin the version
# updatecli.yamlpath == the yamlpath to update; probably should be defaulted.
# updatecli.trim_prefix == defaults to ''
just:
  repo: casey/just
  version: 1.32.0
  artifact: just-{version}-x86_64-unknown-linux-musl.tar.gz
  contents: just
  updatecli:
    yamlpath: $.just.version
    kind: semver
    pattern: "*"
    trim_prefix: v
kubectx:
  repo: ahmetb/kubectx
  version: v0.9.5
  artifact: kubectx_{tag}_linux_x86_64.tar.gz
  contents: kubectx
k9s:
  repo: derailed/k9s
  version: v0.32.5
  artifact: k9s_Linux_amd64.tar.gz
  contents: k9s
terraform-docs:
  repo: terraform-docs/terraform-docs
  version: v0.18.0
  artifact: terraform-docs-{tag}-linux-amd64.tar.gz
  contents: terraform-docs
nova:
  repo: fairwindsops/nova
  version: v3.9.0
  artifact: nova_{version}_linux_amd64.tar.gz
  contents: nova
updatecli:
  repo: updatecli/updatecli
  version: v0.80.0
  artifact: updatecli_Linux_x86_64.tar.gz
  contents: updatecli
tflint:
  repo: terraform-linters/tflint
  version: v0.52.0
  artifact: tflint_linux_amd64.zip
  contents: tflint
gopass:
  repo: gopasspw/gopass
  version: v1.15.13
  artifact: gopass-{version}-linux-amd64.tar.gz
  contents: gopass
tfsummarize:
  repo: dineshba/tf-summarize
  version: v0.3.10
  artifact: tf-summarize_linux_amd64.tar.gz
  contents: tf-summarize
starship:
  repo: starship/starship
  version: v1.19.0
  artifact: starship-x86_64-unknown-linux-gnu.tar.gz
  contents: starship
shellcheck:
  repo: koalaman/shellcheck
  version: v0.10.0
  artifact: shellcheck-{tag}.linux.x86_64.tar.xz
  contents: shellcheck-{tag}/shellcheck:shellcheck
shfmt:
  repo: mvdan/sh
  version: v3.8.0
  artifact: shfmt_{tag}_linux_amd64
  contents: :shfmt
hcledit:
  repo: minamijoyo/hcledit
  version: v0.2.11
  artifact: hcledit_{version}_linux_amd64.tar.gz
  contents: hcledit
tfupdate:
  repo: minamijoyo/tfupdate
  version: v0.8.2
  artifact: tfupdate_{version}_linux_amd64.tar.gz
  contents: tfupdate
gron:
  repo: tomnomnom/gron
  version: v0.7.1
  artifact: gron-linux-amd64-{version}.tgz
  contents: gron
git-cliff:
  repo: orhun/git-cliff
  version: v2.4.0
  artifact: git-cliff-{version}-x86_64-unknown-linux-gnu.tar.gz
  contents: git-cliff-{version}/git-cliff:git-cliff
git-absorb:
  repo: tummychow/git-absorb
  version: 0.6.15
  artifact: git-absorb-{version}-x86_64-unknown-linux-musl.tar.gz
  contents: git-absorb-{version}-x86_64-unknown-linux-musl/git-absorb:git-absorb
committed:
  repo: crate-ci/committed
  version: v1.0.20
  artifact: committed-{tag}-x86_64-unknown-linux-musl.tar.gz
  contents: ./committed:committed
actionlint:
  repo: rhysd/actionlint
  version: v1.7.1
  artifact: actionlint_{version}_linux_amd64.tar.gz
  contents: actionlint
mikefarah-yq:
  repo: mikefarah/yq
  version: v4.44.2
  artifact: yq_linux_amd64
  contents: :yq
mutagen:
  repo: mutagen-io/mutagen
  version: v0.17.6
  artifact: mutagen_linux_amd64_{tag}.tar.gz
  contents: mutagen
lazygit:
  repo: jesseduffield/lazygit
  version: v0.43.1
  artifact: lazygit_{version}_Linux_x86_64.tar.gz
  contents: lazygit
goenv:
  repo: ankitcharolia/goenv
  version: 1.1.8
  artifact: goenv-linux-amd64.tar.gz
  contents: goenv
difftastic:
  repo: wilfred/difftastic
  version: 0.59.0
  artifact: difft-x86_64-unknown-linux-gnu.tar.gz
  contents: difft
gitsemver:
  repo: psanetra/git-semver
  version: v1.1.1
  artifact: git-semver_{version}_linux_amd64.tar.gz
  contents: git-semver
iamlive:
  repo: iann0036/iamlive
  version: v1.1.10
  artifact: iamlive-{tag}-linux-amd64.tar.gz
  contents: iamlive
qv:
  repo: timvw/qv
  version: v0.8.4
  artifact: qv-{version}-x86_64-unknown-linux-musl-generic.tar.gz
  contents: qv
  updatecli:
    pattern: v0.8.4
    # consider pinning because 0.9.6 has no downloadable binaries
    yamlpath: $.qv.version
gitleaks:
  repo: gitleaks/gitleaks
  version: v8.18.4
  artifact: gitleaks_{version}_linux_x64.tar.gz
  contents: gitleaks
jf:
  repo: sayanarijit/jf
  version: v0.6.2
  artifact: jf-x86_64-unknown-linux-gnu.tar.gz
  contents: jf
fzf:
  repo: junegunn/fzf
  version: v0.54.2
  artifact: fzf-{version}-linux_amd64.tar.gz
  contents: fzf
fd:
  repo: sharkdp/fd
  version: v10.1.0
  artifact: fd-{tag}-x86_64-unknown-linux-gnu.tar.gz
  contents: fd-{tag}-x86_64-unknown-linux-gnu/fd:fd
bat:
  repo: sharkdp/bat
  version: v0.24.0
  artifact: bat-{tag}-x86_64-unknown-linux-gnu.tar.gz
  contents: bat-{tag}-x86_64-unknown-linux-gnu/bat:bat
snyk:
  repo: snyk/cli
  version: v1.1292.1
  artifact: snyk-linux
  contents: :snyk
drivel:
  repo: hgrsd/drivel
  version: v0.2.2
  artifact: drivel-x86_64-unknown-linux-gnu.tar.xz
  contents: drivel-x86_64-unknown-linux-gnu/drivel:drivel
dive:
  repo: wagoodman/dive
  version: v0.12.0
  artifact: dive_{version}_linux_amd64.tar.gz
  contents: dive
