name: dependabot-merge

on:
  pull_request:


permissions: {}

jobs:
  bootstrap:
    name: Pipeline Bootstrap
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      actions_modified: ${{ steps.changes.outputs.workflows_any_changed }}
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Changed Files
        # Attempt to figure out what files have changed
        id: changes
        uses: tj-actions/changed-files@ae82ed4ae04587b665efad2f206578aa6f0e8539 # v42.0.0
        with:
          files_yaml: |
            workflows:
              - ".github/workflows/**"

  actions_merge:
    needs: bootstrap
    permissions:
      contents: write
      pull-requests: write
    if: |
      github.actor == 'dependabot[bot]' &&
      needs.bootstrap.outputs.actions_modified == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Find associated PR
        uses: jwalton/gh-find-current-pr@v1.3.1
        id: findpr
        with:
          github-token: ${{ github.token }}
          state: open
          sha: ${{ github.event.pull_request.head.sha || github.event.workflow_run.head_sha || github.sha }}
      - name: merge-actions
        continue-on-error: true
        uses: fastify/github-action-merge-dependabot@59fc8817458fac20df8884576cfe69dbb77c9a07 # v3.9.1
        with:
          pr-number: ${{ steps.findpr.outputs.pr }}
          target: minor
