name: dependabot-merge
run-name: Assess PR (${{ github.event.client_payload.detail.pull_request }})
on:
  repository_dispatch:
    types:
      - test-complete-trigger

permissions: {}

jobs:
  actions_merge:
    if: github.event.client_payload.base.actor == 'dependabot[bot]'
    uses: quotidian-ennui/workflows-olio/.github/workflows/action-dependabot-merge.yml@bc5a8ca54a283873850632edff9d64a78431e63c # v2.2.3
    with:
      client_id: ${{ vars.WORKFLOW_UPDATE_CLIENT_ID }}
    secrets:
      app_private_key: ${{ secrets.WORKFLOW_UPDATE_KEY }}
