name: dependabot-merge
run-name: Assess PR (${{ github.event.client_payload.detail.pull_request }})
on:
  repository_dispatch:
    types:
      - test-complete-trigger

permissions: {}

jobs:
  actions_merge:
    if: github.event.client_payload.base.actor == 'dependabot[bot]'
    uses: quotidian-ennui/workflows-olio/.github/workflows/action-dependabot-merge.yml@eff82979a276acf5fdad410c646fc2527dbc3331 # v2.2.4
    with:
      client_id: ${{ vars.WORKFLOW_UPDATE_CLIENT_ID }}
    secrets:
      app_private_key: ${{ secrets.WORKFLOW_UPDATE_KEY }}
