name: pr-trigger
run-name: PR Build Trigger
on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  depbot-repo-dispatch:
    permissions:
      contents: write
      pull-requests: read
    runs-on: ubuntu-latest
    name: PR Trigger
    steps:
      - name: dispatch
        uses: quotidian-ennui/actions-olio/pr-trigger@62c2311929dae0037513a7c06bab420d9d4353d3 # v1.2.1
